###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Jhonny C",
  "email": "jhonnycal23@gmail.com",
  "password": "1234abcd13123123123"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/632f79d2d0a2768ccac1fd2b HTTP/1.1

###
PUT http://localhost:9000/api/users/63322e992d1ae79966c4e14f HTTP/1.1
Content-Type: application/json

{
  "name": "Jhonny Calvoo",
  "email": "jhonnycalvo1234@gmail.com",
  "password": "1234abc"
}

###
DELETE http://localhost:9000/api/users/633327f170892a1cfdfa5114 HTTP/1.1